import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "./_utils/auth-context";

export const metadata = {
  title: "Artisan Track",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` `}
      >
         <AuthContextProvider>{children}</AuthContextProvider>
      </body>
      
    </html>
  );
}
